export const profile = {
  name: 'Manish Jain',
  first: 'MANISH',
  last: 'JAIN',
  role: 'Digital Marketing & Social Media Strategist',
  tagline: 'Brand, content and event-led growth — measured in numbers, not adjectives.',
  location: 'Delhi, India',
  email: 'manish009work@gmail.com',
  phone: '+91 91314 45130',
  phoneHref: '+919131445130',
  linkedin: 'linkedin.com/in/manishjain2004',
  linkedinHref: 'https://linkedin.com/in/manishjain2004',
  about:
    'I am a digital marketing and social media professional with a BBA in Marketing & International Business. I blend social and content strategy with brand and event execution — from building a seven-pillar content system for a growth agency to leading a national event that welcomed 2,500+ visitors and 65+ exhibiting teams. I like the part where strategy meets a spreadsheet, and then meets a crowd.',
}

export const metrics = [
  { value: '35+', label: 'School teams' },
  { value: '30+', label: 'Institute teams' },
  { value: '15', label: 'Exciting themes' },
  { value: '280+', label: 'Students' },
  { value: '750+', label: 'Registrations' },
  { value: '2,500+', label: 'Toycathon visitors' },
  { value: '65+', label: 'Exhibitor sign-ups' },
  { value: '30%', label: 'Engagement, up from 5–10%' },
  { value: '20+', label: 'Reels scripted and designed' },
  { value: '7', label: 'Content pillars designed & adopted' },
]

export const services = [
  {
    number: '01',
    name: 'Brand & Event Marketing',
    description:
      'End-to-end marketing for large-scale events — brand positioning, on-ground execution and sponsor relationships that hold up under a live crowd.',
    tags: ['Positioning', 'On-ground', 'Sponsors'],
  },
  {
    number: '02',
    name: 'Social Media & Content',
    description:
      'Content calendars, reels, carousels and multi-channel campaigns across Instagram, LinkedIn, WhatsApp and email.',
    tags: ['Calendars', 'Copywriting', 'Canva'],
  },
  {
    number: '03',
    name: 'Influencer & Sponsorship',
    description:
      'Pitching and closing partnerships with company leads, founders, CEOs and investors — plus the follow-through after the handshake.',
    tags: ['Pitching', 'Partnerships', 'Negotiation'],
  },
  {
    number: '04',
    name: 'Performance Marketing',
    description:
      'Testing and optimising messaging and targeting — the work that turned single-digit campaign engagement into 30% inside a fortnight.',
    tags: ['A/B testing', 'Targeting', 'Optimisation'],
  },
  {
    number: '05',
    name: 'Research & Reporting',
    description:
      'Audience and competitor research, campaign reporting and client-facing proposals that turn data into a clear next action.',
    tags: ['Excel', 'Audience mapping', 'Reporting'],
  },
]

export const experience = [
  {
    number: '01',
    role: 'Social Media Marketing Intern',
    company: 'Margo Digitech',
    meta: 'Growth agency · On-site · Delhi',
    period: 'Sep 2026',
    stat: '7 pillars',
    statLabel: 'Content strategy + SOP system adopted for ongoing execution',
    tags: ['Social strategy', 'Content systems', 'Reels', 'SOPs'],
    bullets: [
      'Conducted brand and competitive research for a 360° growth agency serving enterprise clients including Swiggy, Axis Bank, Paytm, PhonePe and HealthKart.',
      'Diagnosed a content distribution and storytelling gap, then built the “Marketing College by Margo” brand positioning and seven-pillar content strategy.',
      'Defined separate platform weighting and messaging styles for LinkedIn and Instagram, with recurring weekly calendars and three-day to 90-day content series.',
      'Authored an internal SOP handbook covering RACI responsibilities, a seven-day production workflow, approval and escalation protocols, and client consent for case studies.',
      'Wrote hook-driven scripts and captions for reels and carousels, and supported 15–20 Instagram Reels across the launch phase.',
      'Presented the complete strategy to leadership; the framework was reviewed and adopted for ongoing content and outreach execution.',
    ],
  },
  {
    number: '02',
    role: 'Sales Executive (Marketing & Outreach)',
    company: 'Aspire Tech – IT Solutions',
    meta: 'International staffing · On-site · Ahmedabad, Gujarat',
    period: 'Jun 2026 – Aug 2026',
    stat: '30%',
    statLabel: 'Engagement, up from a 3–10% campaign baseline',
    tags: ['Campaign testing', 'Targeting', 'AI content', 'Excel'],
    bullets: [
      'Planned and executed multi-channel marketing and outreach campaigns across email, professional networks and personalised messaging.',
      'Identified underperformance in the standard campaign and redesigned messaging and targeting, lifting conversion to 30% within two weeks through an A/B-tested, data-led approach.',
      'Used AI tools to generate personalised campaign content at scale, improving response rates while reducing production time.',
      'Tracked campaign and content performance in Excel, translating engagement data into clear next actions.',
    ],
  },
  {
    number: '03',
    role: 'University Innovation Ambassador',
    company: 'PIERC, Parul University',
    meta: 'Incubation Center · Vadodara, Gujarat',
    period: 'Sep 2023 – Apr 2026',
    stat: '2,500+',
    statLabel: 'Visitors · 65+ exhibiting teams · 280+ participants',
    tags: ['Event marketing', 'Brand positioning', 'Sponsorships', 'Canva'],
    bullets: [
      'Owned the complete event lifecycle for Vadodara Toycathon 2025 — concept, budgeting, vendor and sponsor coordination, logistics and on-the-day execution across 15 categories.',
      'Planned social media and content promotion across Instagram, WhatsApp and email using Canva, briefing collaborators on visuals and deadlines.',
      'Pitched, negotiated and closed sponsorship and influencer-style brand partnerships with company leads, industry leaders, founders, CEOs and investors.',
      'Supervised staff and volunteers on event days, coordinating real-time logistics and issue resolution for a smooth experience across 2,500+ attendees.',
      'Drove college and school outreach that mobilised 500+ student participants, then tracked engagement in Excel to refine messaging and channel choice.',
    ],
  },
  {
    number: '04',
    role: 'Marketing Executive',
    company: 'SG Infra',
    meta: 'Government tenders · Brand documentation',
    period: 'Jan 2025 – Dec 2025',
    stat: 'Multi',
    statLabel: 'Campaign cycles, one consistent brand voice',
    tags: ['Market research', 'Proposals', 'Brand docs'],
    bullets: [
      'Conducted market research and vendor/audience mapping for government tender campaigns.',
      'Prepared client-facing marketing proposals and brand documentation.',
    ],
  },
]

export const toolkit = [
  'Marketing Strategy',
  'Brand Positioning',
  'Event Marketing',
  'Content Calendars',
  'Reel Scripting',
  'Copywriting',
  'Influencer Partnerships',
  'Sponsorship',
  'Campaign Testing',
  'Instagram',
  'LinkedIn',
  'WhatsApp',
  'Email Marketing',
  'Canva',
  'Excel',
  'Market Research',
  'Audience Targeting',
  'Community Engagement',
  'ChatGPT',
  'Gemini',
  'Claude',
  'Copilot',
]

export const credentialsRowOne = [
  'MoE Innovation Cell — Govt. of India',
  'AICTE Innovation Ambassador',
  'PIERC · Parul University',
  'Vadodara Toycathon 2025',
  '2,500+ Visitors',
  '65+ Exhibitors',
  'Brand Positioning',
  'Event Marketing',
]

export const credentialsRowTwo = [
  'Aspire Tech — IT Solutions',
  'SG Infra',
  'Performance Marketing',
  '30% Engagement Lift',
  'Content Calendars',
  'Instagram · LinkedIn · Email',
  'Excel Bootcamp',
  'Market Research',
]

export const awards = [
  {
    title: 'Featured by MoE Innovation Cell',
    body: 'Featured by the Ministry of Education Innovation Cell (Government of India) for leading marketing and event execution of Toycathon 2025.',
    year: 'Oct 2025',
  },
  {
    title: 'Innovation Ambassador — MoE · IIC · AICTE',
    body: 'Recognised as an Innovation Ambassador for the 2024–25 cohort.',
    year: '2024–25',
  },
  {
    title: 'BBA — Marketing & International Business',
    body: 'Parul Institute of Business Administration, Parul University, Vadodara.',
    year: 'Jul 2023 – Apr 2026',
  },
  {
    title: 'Marketing certifications',
    body: 'Excel Bootcamp (Advanced Spreadsheet) · Social Media Marketing Bootcamp (Digital Campaign Strategy).',
    year: 'Bootcamps',
  },
]

/*
  Media is intentionally data-driven. To add your own work, add an item here:
  - certificate: set type to "certificate" and add an image path in /public or a URL
  - picture: set type to "picture" and add the image path/URL
  - reel: set type to "reel" and add the Instagram URL in link
*/
export const portfolioMedia = [
  {
    id: 'toycathon-2025-certificate',
    type: 'certificate',
    eyebrow: 'Vadodara Innovation Fest 2025',
    title: 'Certificate of appreciation',
    subtitle: 'Student Coordinator · Hackathon 6.0 & Toycathon 2025',
    description: 'Recognised for serving as a Student Coordinator for the Vadodara Innovation Fest 2025, including Vadodara Hackathon 6.0 and Vadodara Toycathon 2025.',
    image: '/media/toycathon-2025-certificate.jpeg',
    link: '',
  },
  {
    id: 'toycathon-certificate-presentation',
    type: 'certificate',
    eyebrow: 'Toycathon 2025',
    title: 'Certificate presentation',
    subtitle: 'Recognition on stage',
    description: 'A moment from the Vadodara Toycathon 2025 recognition ceremony.',
    image: '/media/toycathon-certificate-presentation.jpeg',
    link: '',
  },
  {
    id: 'toycathon-team',
    type: 'picture',
    eyebrow: 'Event team',
    title: 'Behind the event',
    subtitle: 'Toycathon & Hackathon 2025',
    description: 'The people and coordination behind the Vadodara Innovation Fest 2025.',
    image: '/media/toycathon-team.jpeg',
    link: '',
  },
  {
    id: 'toycathon-award',
    type: 'picture',
    eyebrow: 'On stage',
    title: 'Toycathon 2025',
    subtitle: 'Event recognition',
    description: 'A captured moment from the Toycathon 2025 award presentation.',
    image: '/media/toycathon-award.jpeg',
    link: '',
  },
  {
    id: 'startup-fest-certificate',
    type: 'certificate',
    eyebrow: 'Vadodara Startup Festival 4.0',
    title: 'Certificate of appreciation',
    subtitle: 'Student Volunteer · February 26–28, 2024',
    description: 'Recognised for contributing as a Student Volunteer at Vadodara Startup Festival 4.0.',
    image: '/media/startup-fest-certificate.jpg',
    link: '',
  },
  {
    id: 'startup-fest-team',
    type: 'picture',
    eyebrow: 'Event team',
    title: 'Startup Festival 4.0',
    subtitle: 'Team and community',
    description: 'A look at the people behind the startup festival experience at Parul University.',
    image: '/media/startup-fest-team.jpg',
    link: '',
  },
  {
    id: 'startup-fest-conversation',
    type: 'picture',
    eyebrow: 'Event conversations',
    title: 'Startup ecosystem',
    subtitle: 'Vadodara Startup Festival 4.0',
    description: 'Conversations and connections from the 2024 startup festival.',
    image: '/media/startup-fest-conversation.jpg',
    link: '',
  },
  {
    id: 'startup-fest-networking',
    type: 'picture',
    eyebrow: 'Event networking',
    title: 'Founder connections',
    subtitle: 'Vadodara Startup Festival 4.0',
    description: 'A festival moment focused on collaboration and the startup ecosystem.',
    image: '/media/startup-fest-networking.jpg',
    link: '',
  },
  {
    id: 'startup-fest-5-certificate',
    type: 'certificate',
    eyebrow: 'Vadodara Startup Festival 5.0',
    title: 'Certificate of appreciation',
    subtitle: 'Student Coordinator · December 12–14, 2024',
    description: 'Recognised for contributing as a Student Coordinator at Vadodara Startup Festival 5.0, organised by PIERC at Parul University.',
    image: '/media/startup-fest-5-certificate.jpeg',
    link: '',
  },
  {
    id: 'startup-fest-5-booth',
    type: 'picture',
    eyebrow: 'Vadodara Startup Festival 5.0',
    title: 'Innovation in action',
    subtitle: 'Exhibitors and event partners',
    description: 'A festival moment from the Startup Festival 5.0 exhibition area.',
    image: '/media/startup-fest-5-booth.jpg',
    link: '',
  },
  {
    id: 'startup-fest-5-team',
    type: 'picture',
    eyebrow: 'Vadodara Startup Festival 5.0',
    title: 'Event team',
    subtitle: 'People behind the festival',
    description: 'A team photograph from the Startup Festival 5.0 experience.',
    image: '/media/startup-fest-5-team.jpg',
    link: '',
  },
  {
    id: 'startup-fest-5-group',
    type: 'picture',
    eyebrow: 'Vadodara Startup Festival 5.0',
    title: 'Festival connections',
    subtitle: 'Coordination and networking',
    description: 'A captured moment from the Startup Festival 5.0 event floor.',
    image: '/media/startup-fest-5-group.jpg',
    link: '',
  },
  {
    id: 'excel-bootcamp',
    type: 'certificate',
    eyebrow: 'LetsUpgrade · December 2024',
    title: 'Excel Bootcamp',
    subtitle: 'Advanced spreadsheet skills · 2 days',
    description: 'Certificate issued after successfully completing the Excel Bootcamp in collaboration with NSDC, ITM Edutech Training and GDG MAD.',
    image: '/media/excel-bootcamp.jpg',
    link: '',
  },
  {
    id: 'social-media-bootcamp',
    type: 'certificate',
    eyebrow: 'LetsUpgrade · April 2025',
    title: 'Social Media Marketing Bootcamp',
    subtitle: 'Digital campaign strategy · 3 days',
    description: 'Certificate issued after successfully completing the Social Media Marketing Bootcamp.',
    image: '/media/social-media-bootcamp.jpg',
    link: '',
  },
  {
    id: 'moe-innovation-reskilling',
    type: 'certificate',
    eyebrow: 'MoE Innovation Cell · 2024–25',
    title: 'Innovation Ambassador',
    subtitle: 'Reskilling training · 21 sessions',
    description: 'MoE and AICTE Innovation Ambassador training certificate for the Reskilling level.',
    image: '/media/moe-innovation-ambassador-reskilling.jpg',
    link: '',
  },
  {
    id: 'moe-innovation-advanced',
    type: 'certificate',
    eyebrow: 'MoE Innovation Cell · 2024–25',
    title: 'Innovation Ambassador',
    subtitle: 'Advanced Level · 30 contact hours',
    description: 'MoE and AICTE Innovation Ambassador training certificate for the Advanced Level.',
    image: '/media/moe-innovation-ambassador-advanced.jpg',
    link: '',
  },
  {
    id: 'moe-innovation-foundation',
    type: 'certificate',
    eyebrow: 'MoE Innovation Cell · 2024–25',
    title: 'Innovation Ambassador',
    subtitle: 'Foundation Level · 30 contact hours',
    description: 'MoE and AICTE Innovation Ambassador training certificate for the Foundation Level.',
    image: '/media/moe-innovation-ambassador-foundation.jpg',
    link: '',
  },
  {
    id: 'margo-certificate',
    type: 'certificate',
    eyebrow: 'Margo Digitech · September 2026',
    title: 'Certificate of achievement',
    subtitle: '3-day internship program',
    description: 'Recognition for successfully completing the 3-Day Internship Program at Margo Digitech.',
    image: '/media/margo-certificate.jpeg',
    link: '',
  },
  {
    id: 'margo-certificate-presentation',
    type: 'picture',
    eyebrow: 'Margo Digitech · On-site Delhi',
    title: 'Certificate presentation',
    subtitle: 'Internship achievement',
    description: 'A moment from the Margo Digitech internship certificate presentation.',
    image: '/media/margo-certificate-presentation.jpeg',
    link: '',
  },
  {
    id: 'margo-team',
    type: 'picture',
    eyebrow: 'Margo Digitech · Team',
    title: 'Strategy in practice',
    subtitle: 'Social media internship',
    description: 'A team moment from the Margo Digitech internship experience.',
    image: '/media/margo-team.jpeg',
    link: '',
  },
  {
    id: 'toycathon-reel-1',
    type: 'reel',
    eyebrow: 'Instagram reel',
    title: 'Toycathon highlight 01',
    subtitle: 'Event stories and moments',
    description: 'Open the original Instagram reel.',
    image: '',
    link: 'https://www.instagram.com/reel/DPlpuSNEnc7/?stkn=MXhyOGk1aDdmdG4zYw==',
  },
  {
    id: 'toycathon-reel-2',
    type: 'reel',
    eyebrow: 'Instagram post',
    title: 'Toycathon highlight 02',
    subtitle: 'Event stories and moments',
    description: 'Open the original Instagram post.',
    image: '',
    link: 'https://www.instagram.com/p/DPlrOsGDOx8/?stkn=NjNsY2dyYXJiNThz',
  },
  {
    id: 'toycathon-reel-3',
    type: 'reel',
    eyebrow: 'Instagram reel',
    title: 'Toycathon highlight 03',
    subtitle: 'Event stories and moments',
    description: 'Open the original Instagram reel.',
    image: '',
    link: 'https://www.instagram.com/reel/DPtZEHkDDQI/?stkn=ZmNmdmhzMGk5eGZx',
  },
  {
    id: 'toycathon-reel-4',
    type: 'reel',
    eyebrow: 'Instagram post',
    title: 'Toycathon highlight 04',
    subtitle: 'Event stories and moments',
    description: 'Open the original Instagram post.',
    image: '',
    link: 'https://www.instagram.com/p/DPttrMakv8p/?stkn=bW5ma2k4OGhzZjR2',
  },
]

export const navLinks = [
  { label: 'About', href: '#about' },
  { label: 'Skills', href: '#skills' },
  { label: 'Experience', href: '#experience' },
  { label: 'Media', href: '#media' },
  { label: 'Contact', href: '#contact' },
]
